### ISSUE TITLE
Infinite Money

### ISSUE THREAD

**Issue by callumio** [KingofKFCJamal/CSGO-Case-Clicker#3]
You can give yourself infinite money by using F12 developer tools and clicking console. You then change any variable you like which you can find in the sources tab in the JS file, then changing the amount of money per click on the accept button. This then allows you to get huge amounts of the money per click. Therefore there is probably a way to give yourself whatever skin you like for free and however many you like. I know this isn't real and a bit of fun, but the players on 'Jackpot' will lose every time when the player comes in with 15 Dragon Lore FN's.

**Comment by speedyplane2247** [comment]
You're playing against bots, not actual people.

**Comment by GUQuakinA** [comment]
how to do this?
